Bump `rubocop-jekyll` to v0.12.x (#63)
Merge pull request 63

diff --git a/script/fmt b/script/fmt
--- a/script/fmt
+++ b/script/fmt
@@ -1,4 +1,9 @@
 #!/bin/bash
 
-echo "Rubocop $(bundle exec rubocop --version)"
-bundle exec rubocop -S -D -E $@
+echo "RuboCop $(bundle exec rubocop --version)"
+bundle exec rubocop -D --disable-pending-cops $@
+success=$?
+if ((success != 0)); then
+   echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
+fi
+exit $success
